server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simply_notify
    username: simply
    password: simply
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: guest
    password: guest
    listener:
      simple:
       missing-queues-fatal: false

logging:
  level:
    root: INFO
    org.springframework.amqp: DEBUG

notification:
  exchange: notifications.exchange
  queue: notifications.queue
  routing-key: notifications.key
  retry:
    max-attempts: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
